query recipeBySlug($slug: String!) {
  recipeCollection(where: { slug: $slug }, limit: 1) {
    items {
      sys {
        id
      }
      title
      description
      imagesCollection {
        items {
          sys {
            id
          }
          description
          thumbnail: url(transform: { width: 350, height: 210, resizeStrategy: FILL, quality: 75 })
          highRes: url(transform: { width: 1200, height: 650 })
        }
      }
      ingredientsList
      directions
    }
  }
}
